### ISSUE TITLE
Did not take effect in jekyll-bootstrap

### ISSUE THREAD

**Issue by Feuda** [d-ogarkov/jekyll-extlinks#1]
![screenshot from 2017-04-17 17 13 12](https://cloud.githubusercontent.com/assets/436635/25084829/52c99dd0-2391-11e7-83e6-a17c94b7286c.png)

![screenshot from 2017-04-17 17 16 39](https://cloud.githubusercontent.com/assets/436635/25084878/a724f2a8-2391-11e7-93d4-e1e6461696ef.png)

![screenshot from 2017-04-17 17 17 25](https://cloud.githubusercontent.com/assets/436635/25085259/cd4197a0-2393-11e7-86b0-568df4896743.png)

**Comment by Feuda** [comment]
Maybe I lost some steps?

**Comment by d-ogarkov** [comment]
I'll check on that.

**Comment by d-ogarkov** [comment]
Are you getting no effect running jekyll-bootstrap locally, or are you running it remotely on GitHub Pages? The ExtLinks plugin works fine with jekyll-bootstrap in my local environment, but it doesn't work on github.io due to security restrictions since it's a user plugin and is not whitelisted (like many others).

**Comment by Feuda** [comment]
Pity, thank you

**Comment by d-ogarkov** [comment]
I sent a message to GitHub Pages support team asking them to whitelist jekyll-extlinks plugin in [pages-gem/lib/github-pages/plugins.rb](https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb).

More info [here](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/):

> GitHub Pages officially supports the Jekyll plugins found in the GitHub Pages gem. For the exact versions of the Jekyll plugins that GitHub Pages supports, see this list of GitHub Pages dependencies. Other plugins are not supported, so the only way to incorporate them in your site is to generate your site locally and then push your site's static files to your GitHub Pages site.
